### ISSUE TITLE
Add session authn tooling to platform

### ISSUE THREAD

**Issue by greatbacon** [feltcoop/felt-server#19]
When looking up user info on the server we should have some sort of tool/util/interceptor to confirm an account is authenticated to access the resources

**Comment by ryanatkn** [comment]
First simplest thing that comes to mind is something like an `authorizeMiddleware` that listens to all `/api/` routes and makes sure an account is attached to the session, otherwise it returns a 401. In the future it could check if that account has access to the requested resource.

`sessionAccountMiddleware` is the current name for the middleware that adds the session account to the request. It might be good to rename to specify that it's *authenticating* the account, so we might have `authenticateMiddleware` alongside `authorizeMiddleware`. (I don't love these names, not sure "account" belongs in there or what)
