### ISSUE TITLE
Use gro for a deploy system

### ISSUE THREAD

**Issue by greatbacon** [feltcoop/felt-server#6]
In order to get the shortest path to production deployments, we want to just use a gro command line (`gro deploy`) to manage deployments to our single instance. More complicated infra will come as we begin to expand.

**Comment by ryanatkn** [comment]
For reference here's Gro's internal `src/deploy.task.ts` for static site deployment using git worktrees and pushing to a "deploy" branch for GitHub pages. It may have some rough edges; I'm about to make a PR using it with Felt, which is a static site project using `@sveltejs/adapter-static`, unlike the server deployment which will be like some variation of `@sveltejs/adapter-node`. (we currently have a hacky implementation, which is fine because this part of SvelteKit isn't yet stable)
